name: "Terraform GitHub Actions CD"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest

    env:
      TF_WORKSPACE: "production"
      TF_ACTIONS_VERSION: 0.12.23

    steps:
    - name: "Code Checkout"
      uses: actions/checkout@v1

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: "init"
        tf_actions_cli_credentials_token: ${{secrets.TERRAFORM_API_TOKEN}}

    - name: "Terraform Apply Staging"
      if: github.ref == 'refs/heads/master'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: "apply"
        tf_actions_cli_credentials_token: ${{secrets.TERRAFORM_API_TOKEN}}
